### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ragmha** [ragmha/eH-learn-es6#1]
- [ ] Learn more about Promises
- [ ] Check use case for generators in Future
- [ ] Check more on Maps and WeakMaps example
- [ ] Check more on rest params
